# keywords: web=voting-app(Django/backend); db=result-app(PostgreSQL);

version: "3"
services:
  web:
    container_name: dev_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    command: python manage.py runserver localhost:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - db
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    image: postgres:15.0-alpine
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  backend:
  database:

volumes:
  static_volume:
  postgres_data:

