# keywords: web=voting-app(Django/backend); db=result-app(PostgreSQL);

version: "3.8"

services:
  web:
    container_name: vote_container
    image: app:vote
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    tty: true
    env_file:
      - ./voting_project/.env
    networks:
      - my_network
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: pg_container
    build:
      context: .
      dockerfile: Dockerfile.db
    image: "postgres:15.0"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
networks:
  my_network:

volumes:
  # static_volume:
  # web_volume:
  postgres_data:

